name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }} ${{ matrix.config.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows MSVC
          os: windows-latest
          deps_cmdline: choco install tree
          build_type: Release

        - name: Windows MSVC
          os: windows-latest
          deps_cmdline: choco install tree
          build_type: Debug

        - name: MacOS LLVM
          os: macos-latest
          extra_options: -DDYN_OPENAL=OFF
          deps_cmdline: brew install tree gawk sdl2 libvpx molten-vk vulkan-volk
          build_type: Release

        - name: MacOS LLVM
          os: macos-latest
          extra_options: -DDYN_OPENAL=OFF
          deps_cmdline: brew install tree gawk sdl2 libvpx molten-vk vulkan-volk
          build_type: Debug

        - name: Linux GCC
          os: ubuntu-latest
          deps_cmdline: sudo apt-get update && sudo apt-get install libsdl2-dev libvpx-dev libwebp-dev waylandpp-dev libbz2-dev libomp-dev libopenal-dev
          build_type: Release

        - name: Linux GCC
          os: ubuntu-latest
          deps_cmdline: sudo apt-get update && sudo apt-get install libsdl2-dev libvpx-dev libwebp-dev waylandpp-dev libbz2-dev libomp-dev libopenal-dev
          build_type: Debug

        - name: Linux LLVM
          os: ubuntu-latest
          extra_options: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          deps_cmdline: sudo apt-get update && sudo apt-get install libsdl2-dev libvpx-dev libwebp-dev waylandpp-dev libbz2-dev libomp-dev libopenal-dev
          build_type: Release

        - name: Linux LLVM
          os: ubuntu-latest
          extra_options: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          deps_cmdline: sudo apt-get update && sudo apt-get install libsdl2-dev libvpx-dev libwebp-dev waylandpp-dev libbz2-dev libomp-dev libopenal-dev
          build_type: Debug

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      shell: bash
      run: |
        if [[ -n "${{ matrix.config.deps_cmdline }}" ]]; then
          eval ${{ matrix.config.deps_cmdline }}
        fi

    - name: Git describe
      id: ghd
      uses: proudust/gh-describe@v2

    - name: Configure
      shell: bash
      run: |
        mkdir build
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DPK3_QUIET_ZIPDIR=ON ${{ matrix.config.extra_options }} .

    - name: Build
      shell: bash
      run: |
        export GIT_DESCRIBE="${{ steps.ghd.outputs.describe }}"
        export MAKEFLAGS=--keep-going
        cmake --build build --config ${{ matrix.config.build_type }} --parallel 4

    - name: Package
      shell: bash
      run: |
        function fetch() { { curl -L "$3" | tee "$1" | sha256sum ; } && { echo "$2 $1" | sha256sum -c - ; } ; }

        cd build
        mkdir package
        packagename="${{ runner.os }}-${{ runner.arch }}"-UZDoom-"${{ steps.ghd.outputs.describe }}"

        7z a package/licenses.zip ../docs/licenses/*

        if [[ "${{ runner.os }}" == 'Windows' ]]; then

            fetch oalsoft.zip \
                ea8bc36fd7fa05f64e13400d20886de753a227202a4ea3781913489a26b36fc6 \
                https://github.com/kcat/openal-soft/releases/download/1.23.1/openal-soft-1.23.1-bin.zip
            unzip -j oalsoft.zip openal-soft-1.23.1-bin/bin/Win64/soft_oal.dll -d package

            fetch sndfile.zip \
                2173935c0c1ed13cf627951d34483f9d405ead2eb473190461c42ba220643a3f \
                https://github.com/libsndfile/libsndfile/releases/download/1.2.2/libsndfile-1.2.2-win64.zip
            unzip -j sndfile.zip libsndfile-1.2.2-win64/bin/sndfile.dll -d package

            mkdir package/soundfonts
            cp ../soundfont/uzdoom.sf2 package/soundfonts

            mkdir package/fm_banks
            cp ../fm_banks/GENMIDI.GS.wopl ../fm_banks/gs-by-papiezak-and-sneakernets.wopn package/fm_banks

            cp ${{ matrix.config.build_type }}/uzdoom.exe ${{ matrix.config.build_type }}/*.pk3 package

            cd package
            7z a -sdel -r "${packagename}.zip" *
            cd ..

        elif [[ "${{ runner.os }}" == 'macOS' ]]; then

            if [[ ! -d uzdoom.app ]] && [[ -d ${{ matrix.config.build_type }}/uzdoom.app ]]; then
                mv ${{ matrix.config.build_type }}/uzdoom.app uzdoom.app
            fi
            mv package/licenses.zip uzdoom.app
            # copy fm_banks + soundfonts ?
            cp -r uzdoom.app package

            cd package
            7z a -sdel -r "${packagename}.zip" *
            cd ..

        elif [[ "${{ runner.os }}" == 'Linux' ]]; then

            ldd ./uzdoom

            mkdir AppDir
            cmake --install . --prefix "$(realpath AppDir)/usr"

            sudo apt-get install libfuse2 # renamed to libfuse2t64 in later releases

            fetch appimage-builder \
                4b4f99cae9291d78ba12dbdabca7c0a67c72aa61eb2e5d424089171a9485e96f \
                https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
            chmod +x appimage-builder

            export GIT_DESCRIBE="${{ steps.ghd.outputs.describe }}"
            ./appimage-builder --skip-tests --recipe ../tools/AppImageBuilder.yml
            mv *.AppImage "package/${packagename}.AppImage"

            rm package/licenses.zip

        fi

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: build/package
        name: ${{ matrix.config.name }} ${{ matrix.config.build_type }}

    - name: List
      if: always()
      shell: bash
      run: |
        git status
        tree -pu build
